"""Rotating REPL tips — how to use Cognition Engine."""

from __future__ import annotations

CE_TIPS: list[str] = [
    "Terminal copy works by default: drag-highlight, then Ctrl+Shift+C.",
    "Use Ctrl+M to open the model picker; use slash commands for actions.",
    "Last assistant reply is always mirrored to ~/.cognition/last_reply.txt for manual copy.",
    "Use PgUp/PgDn to scroll the active pane.",
    "Ctrl+M opens the searchable model picker.",
    "Change model with Ctrl+M or /model MODEL_ID — keys auto-match provider.",
    "Simple questions use quick reply; file/command tasks use agent tools.",
    "Setup keys once — stores DeepSeek under deepseek, not openai.",
    "Generate plan after /goal — builds 8–24 phases in DNA.",
    "/start writes .cognition/bootstrap.md for Cursor or Claude Code.",
    "/end saves session memory and runs reinforcement-learning token allocation.",
    "/shield explains Hallucination Shield (import/API validation).",
    "/status shows phase progress and shield stats.",
    "/memory lists what CE remembers from past sessions.",
    "Shield blocks bad Python on agent write_file automatically.",
    "Token counts live in the top strip (right side).",
    "Esc cancels a running model request.",
    "Agent trace (right) shows every tool step in real time.",
    "Use agent mode: ask to create files, run pytest, grep, delete, etc.",
    "Quick mode: explain concepts, who are you, how CE works — no tool loop.",
    "On Kali: sudo apt install -y xclip if you pipe last_reply.txt to the clipboard.",
    "Linux paste in terminal: Ctrl+Shift+V or middle-click.",
    "Set CE_APP_MOUSE=1 only if you prefer mouse clicks over terminal-native copy.",
    "Git identity: Cursor Settings → Git + ~/.cognition/config.yaml git.user_name.",
    "Project must be initialized (green dot) before /start and /plan.",
    "Track progress button runs /status in the sidebar.",
    "Hallucination Shield uses a truth database — run cognition-engine index once.",
    "Session commits: set git.user_name in ~/.cognition/config.yaml.",
    "Install updates: curl install-ce.sh from GitHub master branch.",
    "Type /help for all slash commands in chat.",
    "DeepSeek models may emit DSML tools — CE runs them automatically.",
    "Approve deletes when prompted — Allow for session remembers choice.",
    "Twenty files? Ask in one message; agent loops write_file per file.",
    "Open examples/xss-finder for a sample CE-managed security project.",
]
